# Generated by Django 4.2.5 on 2023-09-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='update',
            new_name='updated',
        ),
    ]
